### ISSUE TITLE
TX button too small

### ISSUE THREAD

**Issue by Dudestarfan** [nostar/dudestar#103]
if possible make the TX button in the main window a little bigger (to small).

The time slot and the color code and the talkgroup should be next to each other. 
Many Thanks

**Comment by N2GYN** [comment]
**Agree.**

**Comment by JosephTheTank13** [comment]
This is becoming an annoyance now, since the only way to TX is by clicking and holding the button. We desperately need a bigger button. Also, toggling PTT and a TX hotkey would be awesome.

**Comment by Slayingripper** [comment]
Once you press it the first time you can just press the space bar to trigger the ptt if the window is in focus.

**Comment by Slayingripper** [comment]
And if that doesn't work you can keep pressing TAB once the window is in focus , you will get a small little highlighted box around the buttons , keep pressing until you get to the TX button.
