### ISSUE TITLE
Build - MacOS BigSur - Audio out pegged

### ISSUE THREAD

**Issue by ws7m** [nostar/dudestar#107]
Cloned and built using Qt 5.15.2.  On TX mic is pegged to zero dB.  No change with mic gain or codec.

**Comment by nostar** [comment]
Launch the app from the terminal and show the output after a connect to anything.

**Comment by ws7m** [comment]
Tried that as suggested.   No output shown in terminal after connect or during TX.  Is there a command line flag or something else I need to enable?

**Comment by ws7m** [comment]
When run from QT and connect this shows in app output:
06:07:58: Starting /Users/mrh/git/build-dudestar-Desktop_Qt_5_15_2_clang_64bit-Debug/dudestar.app/Contents/MacOS/dudestar ...
ESSID ==  "None"
check_permission() returned 3
CONN: 57 53 37 4d 20 20 20 20 43 43 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
RECV: 44 43 53 30 30 31 20 43 20 57 53 37 4d 20 20 20 43 43 0a 00 20 20 
RECV: 57 53 37 4d 20 20 20 20 43 43 41 43 4b 0a 
Playback device name =  "Jabra UC VOICE 150 duo"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(44100)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "MacBook Pro Speakers"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(48000, 96000, 44100, 88200)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "FlexSliceD"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "FlexSliceB"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "FlexTX"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "FlexSliceA"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "MacSpeaker"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "FlexSliceC"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Playback device name =  "Loopback Audio"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using playback device MacSpeaker
Capture device name =  "Jabra UC VOICE 150 duo"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(44100)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "MacBook Pro Microphone"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(48000, 96000, 44100, 88200)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "FlexSliceD"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "FlexSliceB"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "FlexTX"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "FlexSliceA"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "MacSpeaker"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "FlexSliceC"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Capture device name =  "Loopback Audio"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(176400, 48000, 22050, 96000, 44100, 88200, 192000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using recording device MacBook Pro Microphone
m_vocoder ==  m_hwtx:m_hwrx == 0:0
RECV: 44 43 53 30 30 31 20 20 0a 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
RECV: 44 43 53 30 30 31 20 43 20 57 53 37 4d 20 20 20 43 43 0a 00 20 20 
RECV: 44 43 53 30 30 31 20 20 0a 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43

**Comment by ws7m** [comment]
When start TX and the mic goes to full this is output:
start_tx()  0   ""
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 00 f8 8a a8 22 d4 a0 46 a6 76 55 2d 16 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 01 9a 80 b0 03 15 b0 56 b2 22 30 4f 93 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 02 ba fb 12 93 3e b8 93 a0 35 32 50 4b 02 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 03 e7 5b cb fd bc 2e eb 60 a9 31 4f 91 03 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 04 8f c5 30 49 be a0 d6 57 ea 70 4e 93 04 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 05 d9 8f 94 c2 1f a4 af f3 1e 32 4f 93 05 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 06 a6 b0 53 74 3b 29 e6 cd d5 75 4f 93 06 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 07 b4 19 32 aa dd a0 cb fc 94 33 4f 93 07 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 08 93 6b 80 a0 9a a4 a3 26 5a 70 4f 93 08 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 09 ba fa d9 bf bd b4 bf 13 b6 16 29 f5 09 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0a e2 3a 5d c6 5a 37 f3 a6 cf 16 29 f5 0a 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0b e6 10 7f f6 bc ae de 92 7a 16 29 f5 0b 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0c ab b1 eb a4 3f 39 8e 31 e5 16 29 f5 0c 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0d fa f3 32 da dc 2f da 12 76 16 29 f5 0d 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0e ba 00 88 11 1b b4 f3 b4 ed 16 29 f5 0e 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 0f f8 ad 34 6b bb a3 e2 e6 9d 16 29 f5 0f 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 10 83 26 bc 61 df 28 de 35 aa 16 29 f5 10 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 11 9a bb d3 bf 9d b7 9f 52 32 16 29 f5 11 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 12 ca 30 30 da ff 2d ee 42 32 16 29 f5 12 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 13 d2 34 a4 23 5f b4 82 e5 7a 16 29 f5 13 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 14 8b 64 80 d3 9c b9 97 25 41 16 29 f5 14 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 00 c1 4a 38 a9 ff 25 9e 24 b0 55 2d 16 15 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 01 fa f6 a8 0b fe 3e 8a 45 7f 30 4f 93 16 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 02 e3 98 c3 dd 5f ac ff 40 ef 84 ca 6e 17 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 03 87 bb 43 ac fb 2f ab 25 9b 31 4f 91 18 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 04 aa 18 1a b3 7e b4 87 81 76 70 5e 84 19 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 05 f7 3b 02 d1 1c a1 c3 a2 e1 32 4f 93 1a 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 06 c4 aa 2e aa 3b 35 ba 80 57 a8 30 93 1b 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
RECV: 20 20 20 20 20 20 20 20 54 61 6c 6b 20 6f 6e 20 44 43 53 30 30 31 20 43 00 e6 de 01 00 00 00 00 44 47 33 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 07 ce 86 a4 33 dd b0 86 75 f9 33 4f 93 1c 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 08 8e 78 d5 bf 3f 3d a7 91 77 d7 0a ec 1d 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SEND:100: 30 30 30 31 00 00 00 44 43 53 30 30 31 20 43 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 44 55 44 45 cc b2 09 fb 0b 8c e1 dc ad cf 21 6b 16 29 f5 1e 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
RECV: 44 43 53 30 30 31 20 43 20 57 53 37 4d 20 20 20 43 43 0a 00 20 20 
RECV: 44 43 53 30 30 31 20 20 0a 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43 
RECV: 44 43 53 30 30 31 20 43 20 57 53 37 4d 20 20 20 43 43 0a 00 20 20 
RECV: 44 43 53 30 30 31 20 20 0a 
PING: 57 53 37 4d 20 20 20 43 00 44 43 53 30 30 31 00 43

**Comment by nostar** [comment]
This is a known issue.  See #50 for details.  I asked for the output to see the capture device you are using.  It looks like you are using 'MacBook Pro Microphone' which is included in the hack, but is not working in your case.  I think your only option for now is to use a USB headset like a mpow headset that has been tested using this hack.  The real fix is in the Qt library and I don't have an ETA for that.

**Comment by ws7m** [comment]
Understood.  I'll try a USB mic and see if better.

**Comment by nostar** [comment]
Test latest git and see if it works with all audio capture devices now.
