### ISSUE TITLE
dudestar stuck on "connecting" to an Allstar node?

### ISSUE THREAD

**Issue by JosephTheTank13** [nostar/dudestar#108]
I've got my own login details, and all the node details put into dudestar when I hit connect it sits on "connecting" for a long time before going back to "connect". In the terminal it is putting out what looks like binary, with "SEND" and "RECV" happening every few seconds. So it is doing something but I don't know what. I'm able to connect to the node using DVSwitch Mobile. The allstar node is uLaw with the AIX2 protocol which dudestar supposedly supports. Any idea why this is happening? I found the youtube video demonstrating it working and the audio quality was superb. I'd love to get it working!

**Comment by nostar** [comment]
Post all of that terminal output data from the beginning.

**Comment by JosephTheTank13** [comment]
Started up dudestar, and clicked connect. Let it run for about 4 minutes before stopping it.

`josephhacker@pop-os:~$ cd dudestar/
josephhacker@pop-os:~/dudestar$ ./dudestar
ESSID ==  "None"
doRequest() called m_filename ==  "/DMRIDs.dat"
process() called
doRequest() called m_filename ==  "/NXDN.csv"
process() called
http_finished() called
Downloaded NXDN.csv
DudeStar::file_downloaded()  "NXDN.csv"
http_finished() called
Downloaded DMRIDs.dat
DudeStar::file_downloaded()  "DMRIDs.dat"
lookup IP =  "kc4rpp.com" : 4560
SEND: 80 01 00 00 00 00 00 03 00 00 06 0d 06 03 6a 6f 65 13 02 00 3c 
RECV: a8 d0 00 01 00 00 00 03 00 01 06 04 
RECV: a8 d0 00 01 00 00 00 13 00 01 06 0e 0e 02 00 02 0f 07 33 33 32 39 32 35 39 06 03 6a 6f 65 
SEND: 80 01 28 d0 00 00 00 28 01 01 06 0d 06 03 6a 6f 65 10 20 36 35 61 31 31 32 33 61 38 62 64 38 37 62 34 38 32 30 38 32 31 31 33 61 39 34 38 34 62 36 61 30 13 02 00 3c 
RECV: a8 d0 00 01 00 00 00 28 01 02 06 04 
RECV: a8 d0 00 01 00 00 00 3b 01 02 06 0f 06 03 6a 6f 65 1f 04 c4 2b 23 83 13 02 00 3c 12 10 02 00 da 94 4c 65 94 95 00 00 00 00 00 00 00 00 02 00 04 08 94 6b 63 34 72 70 70 94 
SEND: 80 01 28 d0 00 00 00 49 02 02 06 04 
SEND: 80 01 00 00 00 00 00 03 00 00 06 01 0b 02 00 02 02 0a 32 31 32 35 35 35 33 34 35 35 04 06 4b 4d 34 4f 56 5a 09 04 00 00 00 04 08 04 00 00 00 04 06 03 6a 6f 65 01 05 34 33 31 39 39 0d 05 34 33 31 39 39 05 0a 69 61 78 2d 63 6c 69 65 6e 74 
RECV: 9d 2e 00 01 00 00 00 03 00 01 06 04 
RECV: 9d 2e 00 01 00 00 00 0a 00 01 06 08 0e 02 00 02 0f 09 38 33 35 31 39 31 34 34 36 06 03 6a 6f 65 
SEND: 80 01 1d 2e 00 00 00 25 01 01 06 09 10 20 32 33 62 63 64 64 63 30 34 66 64 63 66 35 37 65 31 38 32 37 33 32 64 65 31 62 64 65 61 63 36 33 
RECV: 9d 2e 00 01 00 00 00 25 01 02 06 04 
RECV: 9d 2e 00 01 00 00 04 10 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 9d 2e 80 01 00 00 04 10 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 9d 2e 80 01 00 00 04 10 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 9d 2e 80 01 00 00 04 10 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
SEND: 80 02 00 00 00 00 00 03 00 00 06 0d 06 03 6a 6f 65 13 02 00 3c 
RECV: b5 1a 00 02 00 00 00 03 00 01 06 04 
RECV: b5 1a 00 02 00 00 00 03 00 01 06 0e 0e 02 00 02 0f 09 31 30 38 38 39 38 32 32 31 06 03 6a 6f 65 
SEND: 80 02 35 1a 00 00 e9 9e 01 01 06 0d 06 03 6a 6f 65 10 20 31 30 36 31 30 38 63 39 66 32 62 37 65 37 31 34 36 31 35 30 31 38 39 39 66 39 31 64 61 33 38 39 13 02 00 3c 
RECV: b5 1a 00 02 00 00 e9 9e 01 02 06 04 
RECV: b5 1a 00 02 00 00 00 18 01 02 06 0f 06 03 6a 6f 65 1f 04 c4 2b 23 a3 13 02 00 3c 12 10 02 00 da 94 4c 65 94 95 00 00 00 00 00 00 00 00 02 00 04 08 94 6b 63 34 72 70 70 94 
SEND: 80 02 35 1a 00 00 e9 ba 02 02 06 04 
SEND: 80 02 00 00 00 00 00 03 00 00 06 01 0b 02 00 02 02 0a 32 31 32 35 35 35 33 34 35 35 04 06 4b 4d 34 4f 56 5a 09 04 00 00 00 04 08 04 00 00 00 04 06 03 6a 6f 65 01 05 34 33 31 39 39 0d 05 34 33 31 39 39 05 0a 69 61 78 2d 63 6c 69 65 6e 74 
RECV: b0 da 00 02 00 00 00 03 00 01 06 04 
RECV: b0 da 00 02 00 00 00 11 00 01 06 08 0e 02 00 02 0f 09 31 32 30 37 36 30 30 30 36 06 03 6a 6f 65 
SEND: 80 02 30 da 00 00 00 20 01 01 06 09 10 20 32 30 61 63 65 33 37 36 36 64 36 62 62 30 31 62 32 36 34 36 34 31 32 65 63 33 30 39 38 61 36 34 
RECV: b0 da 00 02 00 00 00 20 01 02 06 04 
RECV: b0 da 00 02 00 00 04 14 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: b0 da 80 02 00 00 04 14 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: b0 da 80 02 00 00 04 14 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: b0 da 80 02 00 00 04 14 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
SEND: 80 03 00 00 00 00 00 03 00 00 06 0d 06 03 6a 6f 65 13 02 00 3c 
RECV: a2 b0 00 03 00 00 00 03 00 01 06 04 
RECV: a2 b0 00 03 00 00 00 11 00 01 06 0e 0e 02 00 02 0f 09 31 32 30 39 36 33 36 36 36 06 03 6a 6f 65 
SEND: 80 03 22 b0 00 00 ea 45 01 01 06 0d 06 03 6a 6f 65 10 20 64 62 32 34 31 62 62 33 65 63 66 64 36 37 39 37 63 30 61 32 66 63 35 33 64 39 32 38 66 33 31 34 13 02 00 3c 
RECV: a2 b0 00 03 00 00 ea 45 01 02 06 04 
RECV: a2 b0 00 03 00 00 00 29 01 02 06 0f 06 03 6a 6f 65 1f 04 c4 2b 23 c3 13 02 00 3c 12 10 02 00 da 94 4c 65 94 95 00 00 00 00 00 00 00 00 02 00 04 08 94 6b 63 34 72 70 70 94 
SEND: 80 03 22 b0 00 00 ea 5e 02 02 06 04 
SEND: 80 03 00 00 00 00 00 03 00 00 06 01 0b 02 00 02 02 0a 32 31 32 35 35 35 33 34 35 35 04 06 4b 4d 34 4f 56 5a 09 04 00 00 00 04 08 04 00 00 00 04 06 03 6a 6f 65 01 05 34 33 31 39 39 0d 05 34 33 31 39 39 05 0a 69 61 78 2d 63 6c 69 65 6e 74 
RECV: 90 4a 00 03 00 00 00 03 00 01 06 04 
RECV: 90 4a 00 03 00 00 00 05 00 01 06 08 0e 02 00 02 0f 09 31 34 36 38 32 34 36 34 34 06 03 6a 6f 65 
SEND: 80 03 10 4a 00 00 00 1b 01 01 06 09 10 20 65 35 66 34 65 38 31 63 37 62 36 66 66 65 61 61 63 37 62 63 63 64 34 31 32 32 33 34 33 65 32 39 
RECV: 90 4a 00 03 00 00 00 1b 01 02 06 04 
RECV: 90 4a 00 03 00 00 04 05 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 90 4a 80 03 00 00 04 05 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 90 4a 80 03 00 00 04 05 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
RECV: 90 4a 80 03 00 00 04 05 01 02 06 06 16 12 4e 6f 20 61 75 74 68 6f 72 69 74 79 20 66 6f 75 6e 64 2a 01 32 
josephhacker@pop-os:~/dudestar$`

**Comment by JosephTheTank13** [comment]
After converting the hex to text, there is mention of "no authority found". Is this a node specific issue? The info I put in is the same as the info I use to log into the node in DVSwitch, so it's correct for sure. Maybe the owner of the node needs to change a setting to allow this client to connect.

**Comment by nostar** [comment]
My only testing has been done on my own node.  I didn't know that repeater nodes allow iax client connections directly.  Instead I iax client connect to my own node and then use my client as a remote control and connect my node anywhere, anytime.

I tried removing the hard coded calling number that I had in there, give latest git a try. You aren't putting anything in for a calling number right?  If no change, I would have to have access to that node myself to troubleshoot this.  If you can arrange that, I will look into this further.

**Comment by JosephTheTank13** [comment]
Updated and recompiled. No change. It does seem to be a bit more active in the terminal now, but it's still the same SEND and RECV with hex. And no, I haven't put anything in for a calling number. I'll talk to the owner of the node and see what we can do about getting you access. I'd really love to get this working so I can use his node on my PC.

**Comment by nostar** [comment]
Try the latest git again, I made some changes to the call frame that makes the initial connect.

**Comment by JosephTheTank13** [comment]
> Try the latest git again, I made some changes to the call frame that makes the initial connect.

That worked! I was able to connect just fine and hear the audio! Really good audio quality I might add. Now to figure out how to compile it for windows and we'll be golden!

**Comment by nostar** [comment]
I'll update the windows builds later tonight and put a new droidstar release with the IAX changes.

**Comment by JosephTheTank13** [comment]
Sweet! If it's not too hard to answer, how do you compile it for windows? I'm well familiar with linux compiling but I haven't seen a standard way to do it on windows. And how would one solve dependencies if you cannot install them onto windows? If it takes too long to answer then don't worry about it. Thank you so much for solving this issue so fast!

**Comment by nostar** [comment]
You have to create a GCC based build system with Qt libs, then its just qmake and make just like on Linux and mac.  The builds I post on github are statically linked executables, not installers and require no external dependencies.  Creatign a build system to make those in a non-trivial task.  I don't even build them in Windows anymore, since I now have a windows cross compiler setup in linux to create these builds.
