### ISSUE TITLE
DVMEGA DVstick30 device not open

### ISSUE THREAD

**Issue by 9V1KG** [nostar/dudestar#110]
Program running fine on Linux Mint 20.1 with the Software vocoder. Using my USB DVMEGA DVstick shown as
"ttyUSB0 - FTDI FT230X Basic UART - DM02GMKV", I get  "QIODevice::write (QSerialPort): device not open",
when someone starts to talk on the channel. Connected to DMR. I am not familiar with C - do I miss something out?

**Comment by nostar** [comment]
Try closing dudestar, unplug the usb device, plug back in, restart dudestar and connect.

**Comment by 9V1KG** [comment]
This was the first thing I already did. Same behavior. By default dudestar always starts with the software decoder, seems, the USB setting is not stored.

**Comment by nostar** [comment]
It is not supposed to be stored, software decoder is the default on purpose.  Now I'm confused, what is the issue?

**Comment by 9V1KG** [comment]
The issue is that I can not use the USB stick. When I switch to ttyUSB0 after starting the program and connect, the SerialPort does not open: QIODevice::write (QSerialPort): device not open

**Comment by nostar** [comment]
Make sure you have permission to open the serial device.  On my fedora system I need to be a member of the group 'dialout'.  Do ls -l /dev/ttyUSB0 and see what group is used on your OS, it is probably also 'dialout'.

**Comment by 9V1KG** [comment]
Yes, same here. I added myself to the 'dialout' group, still the same message.

**Comment by nostar** [comment]
Did you log out and log back in after adding yourself to the group?

**Comment by 9V1KG** [comment]
Do I need to uncheck SWTX SWRX?

**Comment by nostar** [comment]
That's not an answer.

**Comment by 9V1KG** [comment]
Sorry, just logged out and in again and same message when I uncheck SWTX SWRX

**Comment by nostar** [comment]
I don't know what you are talking about now.

**Comment by 9V1KG** [comment]
I am shown as member of 'dialout' now.
In the main window of the dudestar program there is a checkbox SWRX and SWTX. I assume this means software receiver (vocoder) and software transmitter (vocoder). As I have a USB hardware dongle, I uncheck. Then I get the error message.

**Comment by nostar** [comment]
When you connect to a host of any mode that uses AMBE and you have selected a USB vocoder, SWTX and SWRX will both be unchecked by default, so I dont know why you are touching them at all.

**Comment by 9V1KG** [comment]
1. When I start the program, both are unchecked. software decoder set by default. 
2. When connecting to a host, both are checked automatically, correct.
3. Disconnecting and selecting USB0 and reconnecting to the host, both unchecked automatically, ok.
4. Transmitting: QIODevice::write (QSerialPort): device not open
So it seems somehow the USB port cannot be opened by the program.

**Comment by nostar** [comment]
unplug the dongle, close dudestar and run `sudo systemctl stop ModemManager.service` then plug in and try again.  Dont connect using software first, no need for that.

**Comment by 9V1KG** [comment]
done. Same message.

**Comment by nostar** [comment]
Do `sudo systemctl disable ModemManager.service` to make it permanent, then restart.  After that pull the latest git and post the terminal output.

**Comment by 9V1KG** [comment]
Ok, seems to work now:

`qt5ct: using qt5ct plugin`
`ESSID ==  "None"`
`dmrid_text_changed() called s ==  "262"`
`'qt5ct: palette support is disabled`
`CONN: 52 50 54 4c 00 50 1b ef `
`RECV: 52 50 54 41 43 4b 67 e1 26 30 `
`SEND: 52 50 54 4b 00 50 1b ef 1d a7 54 c4 d2 06 34 db 0a e5 d2 4c 63 49 68 d2 b5 99 0f bb c2 76 13 b2 b0 f5 67 f1 d1 20 2d 2a `
`RECV: 52 50 54 41 43 4b 00 50 1b ef `
...
`SENDHW 17:0:61 00 0d 00 0a 04 31 07 54 24 00 00 00 00 00 6f 48 `
`Using playback device alsa_output.usb-MOTU_M4_M40000008199-00.analog-surround-40`
`Using recording device alsa_input.pci-0000_00_1b.0.analog-stereo`
`AMBEHW 12:12:61 00 02 00 3f 00 61 00 02 00 0a 00 `
`PING: 52 50 54 50 49 4e 47 00 50 1b ef `
`RECV: 4d 53 54 50 4f 4e 47 00 50 1b ef `
`start_tx()  0   ""`
`AMBEHW 15:15:61 00 0b 01 01 48 95 4b e6 50 03 10 b0 07 77 `
`AMBEHW 15:15:61 00 0b 01 01 48 82 f6 e1 97 bb 88 00 23 f3 `
`AMBEHW 15:15:61 00 0b 01 01 48 99 0a ee 53 8a 1c 99 27 63 `
`SEND:55: 44 4d 52 44 00 50 1b ef 00 01 06 00 50 1b ef a1 fa 3c 00 00 05 0e 00 ae 03 c0 0c 40 29 30 36 01 04 6d 5d 7f 77 fd 75 7e 33 48 3f e0 1e 60 45 21 34 00 73 02 95 00 00 `
`AMBEHW 15:15:61 00 0b 01 01 48 6a b1 e3 32 62 0e 01 d6 6b `
...
Thank you!

**Comment by nostar** [comment]
I didn't do anything since yesterday except add debug output.  I think stopping the ModemManager wasn't enough, it needed to be disabled and rebooted.

**Comment by 9V1KG** [comment]
Yes, maybe this was the problem. Should be stated in the docu. Thanks, excellent. Finally I have a solution under Linux with my Ambe stick.

**Comment by nostar** [comment]
Technically this is just a general Linux serial device issue, not a dudestar issue.  You wouldn't have been able to use that or any USB serial device in Linux without adding yourself to the dialout group and disabling ModemManager.  I made a note of it in the README though.

Pull the latest git to get rid of the debug out.  Your stderr will be flooded with AMBE data and could cause performance issues.

**Comment by 9V1KG** [comment]
Ok, thank you!
