### ISSUE TITLE
Unable to connect to XRF012

### ISSUE THREAD

**Issue by clewisit** [nostar/dudestar#118]
A local repeater club uses XRF012 A for their D-Star bridge.  When I try to connect using dudestar, it says "Connecting" and never connects.  The log just shows "Connecting to 216.240.173.55:30001..."

Dudestar is able to connect to other X-Reflectors, and BlueDV is able to connect to XRF012, so I'm not sure what the issue could be, or how to troubleshoot it further.

**Comment by nostar** [comment]
There is a new option in latest git under Dstar Settings 'Connect to XRF using REF (DPlus) protocol'.  Check this option for XRF012 or any other XRF reflector that is not XLX based.

**Comment by nostar** [comment]
FYI you should use your USB AMBE device if you plan on transmitting on Dstar.  The software vocoder is unacceptable quality for Dstar TX.

**Comment by clewisit** [comment]
Very cool.  That reflector works now.  Thanks for the quick fix, and I will keep in mind your warning regarding transmitting on Dstar.
