### ISSUE TITLE
Ping Slowly Rising?

### ISSUE THREAD

**Issue by sriddle724** [nostar/dudestar#119]
Maybe it's something that I'm missing maybe it's an actual issue. I noticed on both the windows and Linux app along with the Android app, that thing will be fantastic and then it's slowly rises I've had it get as high as 600 milliseconds on me. Any clue or what the problem could be? If I disconnect and reconnect it drops again but then it slowly rises the longer than it sits there. 
TIA

**Comment by nostar** [comment]
Where does it say milliseconds?  It's a count of ping responses.
