### ISSUE TITLE
Error compiling on macOS Big Sur

### ISSUE THREAD

**Issue by yoramrotbach** [nostar/dudestar#124]
Hi,

Getting the following error while in the make step:

Undefined symbols for architecture x86_64:
  "_objc_msgSend", referenced from:
      MicPermission::check_permission() in micpermission.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dudestar.app/Contents/MacOS/dudestar] Error 1

I would appreciate if this can be looked at.

73 de Yoram 4Z1YR

**Comment by nostar** [comment]
Your build system is broken.
