### ISSUE TITLE
Increase the size of the Talkgroup box

### ISSUE THREAD

**Issue by WS4BSA** [nostar/dudestar#127]
In both the x64 and x86 windows version the text box for the Talkgoup is too small.  It currently configure for 5 digits.  The Talkgoup that I am using is 6 digits.  The Talkgroup ID that I am using is 311037 and is for the BRARA radio club. Please increase the size textbox to view at lest 6 digits and for future proofing  expand it out to 8 digits.

**Comment by nostar** [comment]
I think its too big.
