### ISSUE TITLE
TX every 6 mins

### ISSUE THREAD

**Issue by atasoyk** [nostar/dudestar#13]
hello, when you listen to a DMR station with a registered call sign it sends a kind of ping with your call sign every 6 minutes and this disturbs people who are on standby with their devices. can you disable this feature?

**Comment by 9A6NDZ** [comment]
I have the same problem. Every 5 minutes. Can you turn off that option please. Thanks

**Comment by atasoyk** [comment]
can we have an answer fır this? people get disturbed every 5 mins due to TX from software and this can't be controlled. You have to disable this option!!

**Comment by nostar** [comment]
If you use Dudestar with AMBE USB hardware, this will not happen, since you are able to TX manually. @atasoyk you have to stop using Dudestar or Droidstar please, I do not take kindly to demands!
