### ISSUE TITLE
What's the point in requiring a valid DMR ID in DroidStar if one plans to use only M17? 

### ISSUE THREAD

**Issue by mlforcada** [nostar/dudestar#151]
Hi Doug.
A friend just found that he cannot use DroidStar for M17 unless he has a DMR ID. 
This also happens in DudeStar.
Could this restriction be modified so that it only applies to DMR connections?
Best,
Mikel EA5IYL

**Comment by robrobinette** [comment]
Your M17 ID is derived from your DMR ID so this may be a difficult fix. The obvious solution is have your friend get a DMR ID even if he doesn't want to run DMR. P25 also uses your DMR ID.

73 de K9OJ

**Comment by mlforcada** [comment]
Thanks, @robrobinette, I didn't know that!

**Comment by nostar** [comment]
M17 IDs are just callsigns and not derived from DMR IDs.  DMR IDs *are* used by XLX multimode servers for cross mode lookups, so it's a good idea to have one these days, even if you never plan to do DMR directly.  Dudestar/Droidstar requires a DMR ID to deter non licensed operators from using this software.

**Comment by robrobinette** [comment]
Sorry about that, I forgot that my M17 ID, 0x0000000A276B, was derived from my callsign, not my DMR ID.
