### ISSUE TITLE
Is Brandmeister blocking both Dude star, and Droid star?

### ISSUE THREAD

**Issue by N2GYN** [nostar/dudestar#155]
Is Brandmeister **blocking** both Dude star, and Droid star? Many are having issues.
De: N2GYN

**Comment by Ahbood** [comment]
Brandmeister is currently blocking masters 3101, 3102, 3103. Your best bet is to use a different master than those and it works fine.

**Comment by TheButterZone** [comment]
Huh?

![Screenshot_20210312-151222](https://user-images.githubusercontent.com/2625857/111008306-a5a57c00-8345-11eb-94e1-f3caa8f48edf.jpg)

**Comment by RadioRedFred** [comment]
The rush of commits and releases the other day makes it pretty clear that BM was/is trying to block Dudestar/Droidstar.  Try using MMDVM_MMDVM_HS_Hat for package ID, this works for me on 3101, 3102, 3103.  Droidstar doesnt have the software ID and package ID options, they must be hard coded to something that apparently works for now.

**Comment by Ahbood** [comment]
Yes sir... Now Brandmiester and Dstar have blocked Droidstar and Dudestar. 
I was just listening to a few guys on C4FM and TGIF complaining about Brandmiester blocking dudestar.




-- 
Aegis Group, LLC
1955 W. Baseline Rd, ste 113-540
Mesa, Az. 85202
Office:480-497-4272 Cell:201-497-4272
License No. 1602890  P.I. License No. 1649919

NOTICE: This email and any attachments are for the exclusive and confidential use of the intended recipient(s). If you are not an intended recipient, please do not read, distribute, or take action in reliance upon this message. If you have received this in error, please notify me immediately by return email and promptly delete this message and its attachments from your computer.

**Comment by RadioRedFred** [comment]
I'm on dstar every day with dudestar and droidstar.
