### ISSUE TITLE
No audio TXing on BM Group Call

### ISSUE THREAD

**Issue by EL375** [nostar/dudestar#158]
No audio when transmitting on BrandMeister as a Group Call. no issues when Txing Private call.
DUDE-Star showing Mic Levels fine and BM showing a talk session but no audio.
9990 Parrot is responding fine as Private Call.
DUDE-Star Windows 64-bit git build 7bc4ac0

Thanks.

**Comment by RadioRedFred** [comment]
Try setting package ID to MMDVM_MMDVM_HS_Hat per this discussion #102

**Comment by EL375** [comment]
Nope, aint working for me :(
Trying all possible names and dates per discussion 102, no result, Private Call works, Group Call dont.
