### ISSUE TITLE
Connection Closing when phone sleeps

### ISSUE THREAD

**Issue by s3m1s0n1c** [nostar/dudestar#163]
Thanks for making this available on IOS

I noticed that the connection gets dropped when the phone sleeps..

Is it possible to have an option to keep it away.. 
Maybe send a ping to the server to keep it active..

This is helpful when listening to say 505 etc while at work on or on the train...

Thanks
VK2FRTS/Sonic

**Comment by nostar** [comment]
For now, this is on purpose.
