### ISSUE TITLE
Bug in Software AMBE decoder?

### ISSUE THREAD

**Issue by hajosc** [nostar/dudestar#165]
I notice on Brandmeister several QSOs (not all) start with about 0.5sec (up to 1.5secs at times) noise at what sounds like max AF level. Reminds me of a transmission error when CRC checking is disabled, kind of "scratchy white noise". Monitoring the same TG on a Ailunce HD1 doesn't exhibit that noise.
Interesting is that those noise parts do not cover any voice, I.e. it kind of looks like that noise is generated in a time-frame between the remote PTT being pressed and the AMBE codec detecting voice?

Sorry for the imprecise description...

**Comment by nostar** [comment]
That's just how mbelib sounds.
