### ISSUE TITLE
Dudestar and Droidstar don't properly generate a random Stream ID - fixed ID 4198236160

### ISSUE THREAD

**Issue by hacknix** [nostar/dudestar#168]
Hi, 

Simon, G7RZU, developer for FreeDMR here. 

I have noticed that Droidstar and Dudestar both don't generate a proper random StreamID for each transmission. Instead they use the same fixed value - 4198236160

This isn't compliant and can cause issues on the network. 

Any chance of fixing this?

Thanks!

73

Simon

**Comment by nostar** [comment]
Yes, I forgot all about this.  Fixed in latest git.

**Comment by hacknix** [comment]
Thanks!
 

On 3 April 2021 20:35:36 BST, nostar ***@***.***> wrote:
>Yes, I forgot all about this.  Fixed in latest git.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nostar/dudestar/issues/168#issuecomment-812915140

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
