### ISSUE TITLE
Windows compiling how to

### ISSUE THREAD

**Issue by kourampies** [nostar/dudestar#17]
I understand the reasoning behind removing the binaries, but some compiling instructions would be nice. I can compile on Linux but don't know how to do it on Windows.

**Comment by ea5gvk** [comment]
Please. Help
The binaries for windows are no longer in the release?
Why?
Help to compile them in windows.
Thank you.

**Comment by brovary3154** [comment]
https://en.wikipedia.org/wiki/Cygwin

You can adapt information from this how to:
https://www.1geniesup.fr/download/Building_DSD_v1_8_4.pdf

**Comment by nostar** [comment]
The windows build is back in the releases section.
