### ISSUE TITLE
QRandomGenerator not declared error on compilation

### ISSUE THREAD

**Issue by crazybyte** [nostar/dudestar#19]
Hello,

I tried to compile dudestar on Ubuntu Linux 18.04. After running the needed commands for compiling and building it the following error is received:

dudestar.cpp: In member function ‘void DudeStar::readyReadREF()’:
dudestar.cpp:2377:11: error: ‘QRandomGenerator’ has not been declared
   int x = QRandomGenerator::global()->bounded(7245, 999999);
           ^~~~~~~~~~~~~~~~
Any suggestions on how to solve or circumvent this issue? Thank you

**Comment by nostar** [comment]
QRandomGenerator requires QT >= 5.10, and Ubuntu 18.04 is packaged with QT 5.9.5.  I replaced with standard C rand() instead.
