### ISSUE TITLE
Would love to help test TX features

### ISSUE THREAD

**Issue by slavik0329** [nostar/dudestar#2]
I saw your Youtube video with P25 software encoding. Will you be releasing this feature? I would love to help with testing. I am a full stack web engineer.

Thanks,
Steve
73 de KD2TTY

**Comment by nostar** [comment]
Hi Steve,

It's already in there.  It will always default to software encoding/decoding for P25 since the AMBE3000 based dongles do not support P25.

**Comment by slavik0329** [comment]
@nostar Is that only available from source? I'm using the windows binary and it doesn't seem to have TX.

**Comment by nostar** [comment]
Are you sure you have the latest binary?  It should be DUDE-Star git build 661bafb.  

For the record I only create a Windows build as a courtesy, and don't do much testing of it.  I did confirm that P25 TX works though.  When you connect to a P25 host, the TX button should become enabled.  With the software encoder, input mic gain and mic quality is very important to get good P25 quality.  The controls on the app do not adjust the levels at the audio driver level, which should be the primary method for level adjustment.  On Linux, I always use pulse audio mixer to set these levels, so on Windows the equivalent system level controls should be used to get good results.

**Comment by mharris7000** [comment]
@nostar Are there plans to make the P25 TX audio adjustable via the app, or more importantly, adding Parrot (TG 10) to the drop-down list on the app?  I'm really enjoying the ability to listen to P25 and would love to be able to test the self-adjusted transmit audio before actually transmitting on a TG.  Thanks for all your hard work on this!

**Comment by nostar** [comment]
I'm not familiar with P25 Reflector 10, but if the reflector info is submitted to the P25Clients project as an issue, it will be added to the reflector list and will show up in the Dudestar list.

Mic gain should be adjusted using the operating system level controls.
