### ISSUE TITLE
Mute button does not provide visual feedback about mute state (mute toggle)

### ISSUE THREAD

**Issue by scresante** [nostar/dudestar#209]
When pressing the mute button for either Volume or Mic Gain in the Main tab, there is no visual feedback that mute mode is engaged.

The usual UX for this situation would be that the slider bar drops to zero upon pressing mute, and restores to the previous value when pressing mute again. Preferably, the mute button would also show the depressed state when activated.

**Comment by nostar** [comment]
Resolved in latest git.
