### ISSUE TITLE
No windows builds avaliable

### ISSUE THREAD

**Issue by wgaylord** [nostar/dudestar#215]
The most recent pre-release mention windows executables but there are none provided anywhere in this repository.

**Comment by wgaylord** [comment]
I would build them myself but I have little to no experience in cross platform building for windows. (Also limit experience building ON windows, although I did get LLVM to build once.)

**Comment by wgaylord** [comment]
Got clearification on Matrix / Discord /IRC

**Comment by dslotter** [comment]
@wgaylord Can you please share the clarification on no Windows builds being available? Otherwise, I'll need to open up a new issue on this... Thanks.

**Comment by wgaylord** [comment]
He was having issues with his setup he used for compiling for windows.

**Comment by dslotter** [comment]
So why delete the existing binaries?
