### ISSUE TITLE
headless version

### ISSUE THREAD

**Issue by hajosc** [nostar/dudestar#22]
Nostar, this seems the only way to contact you, sorry...

Are you still actively developing the excellent dudestar? It requires very little resources, runs very well on a Raspberry. Wondering whether you're considering to add command-line options for headless use. If not, are you willing to entertain another contributor to add this? If you consider dudestar code-complete I might just fork it and do it myself, but I hate to branch off of stuff someone else owns and still intends to work on...
Not sure whether I will get around to it, but a headless Raspberry with dudestar and some HW could make for a very, very nice handheld "Wifi HAM radio"...

**Comment by nostar** [comment]
I'm tied up with other projects for most of the summer but I hope to get back into it in the fall or winter.  A headless version of Dudestar doesn't really interest me, but I have added TX abilities to my Droidstar app, which is based off Dudestar.  When I get back into this stuff that will all be released and explained in detail.  In the meantime, you can always fork this and any other github open source project and go crazy with it.  Thats the nature of github.
