### ISSUE TITLE
Windows build fails to launch - This application failed to start because no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by dslotter** [nostar/dudestar#224]
Since there's no longer pre-build Windows binaries available under github.com/nostar/dudestar/releases I decided to build my own. Not exactly a seamless process, but anyway, I end up with dudestar.exe built under my source\dudestar\release directory and it is 1.69 MB in size (1,781,760 bytes).

Launching this app results in a dialog displaying: "This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

I ran the "Depends" tool and it shows that all Qt5 DLLs and system DLLs are present.

Please either provide release executables to download or a better explanation on how to build the Windows version. I do consider lack of reasonable documentation to be a defect / bug.

**Comment by nostar** [comment]
*NO support for Windows builds, either building or using.*

Do not do this again.
