### ISSUE TITLE
DMR ID Text Field too short to display 7 digit DMR ID

### ISSUE THREAD

**Issue by dslotter** [nostar/dudestar#226]
This one is pretty simple. Only 6 digits of a 7 digit DMR ID will show in the DMR ID field -- the 7th digit will not be displayed.

There is sufficient room in the UI to make the DMR ID field wider. Request that it be made wider to accommodate at least a 7 digit DMR ID, please.

**Comment by nostar** [comment]
the DMR TGID field was lengthened months ago.  As instructed in the issues text, only post issues using the latest git on Linux.
