### ISSUE TITLE
DUDE-Star (and DroidStar) blocked on REF030 and REF001 on D-Star

### ISSUE THREAD

**Issue by dslotter** [nostar/dudestar#227]
I tried using REF030 on D-Star and found I was blocked from sending/receiving on the reflector. I additionally received this email:

> Your callsign has been logged on either REF001 or REF030 using the dudestar or droidstar software. This software is experimental and has caused problems on the busy reflectors. As a result, the administrators of the reflector have blocked you on the reflector you were using it on.
>  
> Please do not use this software on Reflectors 001 and 030. Let me know if you discontinue use on these reflectors and I will request you to be unblocked.
>

**Comment by nostar** [comment]
There is nothing wrong with dudestar and D-Star.  This is a political issue with the REF001/REF030 Nazis.
