### ISSUE TITLE
Array overflow in readyReadDMR

### ISSUE THREAD

**Issue by DieGoldeneEnte** [nostar/dudestar#25]
In [dudestar.cpp line 2100](https://github.com/nostar/dudestar/blob/9589eee662a8a42568a58dc6d7c74b2b572fcc03/dudestar.cpp#L2100) the `memcpy` is going one byte over the bound of the array. This is the case for dmrframe (start at the 21th byte and read until the 34th byte, but we only have 33) and also for dmr3ambe (start at 15th byte end at 28th, but only have 27).

gcc9 is giving a warning: `‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ forming offset 28 is out of the bounds [0, 27] of object ‘dmr3ambe’ with type ‘uint8_t [27]’ {aka ‘unsigned char [27]’} [-Warray-bounds]`

On receiving DMR-Audio the program crashes.

**Comment by nostar** [comment]
The size of dmrframe is ok, but dmr3ambe was short by 1.

**Comment by DieGoldeneEnte** [comment]
I don't know what is actually happening here, so this might be totally wrong, but:

The dmrframe is to small, maybe `memcpy` only needs to copy 13 bytes? With your last change (5cb8d0f13f05b39c6e197dc3318bb05810497c5e) you still read out-of-bound. gcc is also still giving me the warning (this time for dmrframe):  `‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ forming offset 34 is out of the bounds [0, 33] of object ‘dmrframe’ with type ‘uint8_t [33]’ {aka ‘unsigned char [33]’} [-Warray-bounds]`. (To also get this warning you need to compile the file with `-Warray-bounds`, at least on gcc9)


If you enlarge the dmr3ambe buffer I think you also need to also increase the counter in the [loop](https://github.com/nostar/dudestar/blob/5cb8d0f13f05b39c6e197dc3318bb05810497c5e/dudestar.cpp#L2102) below. At the moment you just ignore the last byte.

**Comment by nostar** [comment]
It's fixed correctly now.
