### ISSUE TITLE
Compile Error Mate Linux X64

### ISSUE THREAD

**Issue by dl1esz** [nostar/dudestar#27]
Hi,
i got this error in sudo make, any idea

Stefan DL1ESZ

elib\build_x32 -LC:\Qt\mbelib\build_x64 -lmbe -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: -lmbe kann nicht gefunden werden
collect2: error: ld returned 1 exit status
Makefile:339: recipe for target 'dudestar' failed
make: *** [dudestar] Error 1
stefan@stefan-ThinkPad-T540p:~/Downloads/dudestar-master$

**Comment by nostar** [comment]
You dont have mbelib installed or not installed correctly.

**Comment by dl1esz** [comment]
Hi nostar,
thanks for info, ive compiled mbelib from this source successfully and made a freh compile from dudestar complete with no error.
So far so good but whe i sart dudestar with ./dudestar or direct the binary in /opt/dudestar/bin/
 i got this error
./dudestar: error while loading shared libraries: libmbe.so.1: cannot open shared object file: No such file or directory

any idea
Stefan DL1ESZ

**Comment by dl1esz** [comment]
Sorry source from mbelib was https://github.com/szechyjs/mbelib
Stefan DL1ESZ

**Comment by nostar** [comment]
When you installed mbelib from source it probably installed to /usr/local/lib or /usr/local/lib64 and these directories are unknown by your linker.  You need to add these directories to your linkers config, something like this:

create a new file local.conf in /etc/ld.so.conf.d and add 2 lines:
```
/usr/local/lib
/usr/local/lib64
```
Save this file then run the command ```sudo ldconfig```

**Comment by dl1esz** [comment]
Thanks nostar,
that was the missing info, now its working well. The audio is acceptable but not similar to BlueDV/DV30 but nice to have with soft AMBE, good job.
BR Stefan DL1ESZ

**Comment by dl1esz** [comment]
Thanks for fine support, and the fine programming job
Issue closed solved
Stefan DL1ESZ

**Comment by nostar** [comment]
Just curious, audio is less quality when using software vocoding for sure, but if you use your AMBE dongle with Dudestar it should sound as good as BlueDV right?

**Comment by dl1esz** [comment]
Hi nostar,
on DV30 AMBE Stick audio (especially RX) is much better but a little rough/raw , settings in Audio optimized but not overdriven, the soft AMBE is like the md380 works but not an acoustic revolution hihi.
Id like to compile it for windows 10 ( as a compare with blueDV, is there a  manual for compile under Win10, what compiler would you choose for win ( Iam  using most Linux but try also Win10 but more or less as a standart user, my programming jobs are only done by linux)
Br Stefan DL1ESZ
