### ISSUE TITLE
Network AMBE Server 

### ISSUE THREAD

**Issue by g4tsn** [nostar/dudestar#3]
Any way to connect to a networked AMBE server please

**Comment by narspt** [comment]
+1

**Comment by nostar** [comment]
No

**Comment by narspt** [comment]
Sorry to ask, but... why? it would be nice for guys using AMBE stick with AMBEServer for other applications, mobile apps, etc... and should be easy to implement, just send/receive same raw AMBE packets to remote udp socket instead of to serial interface... please consider it...

**Comment by nostar** [comment]
My interests are in vocoder methods that do not rely on DVSI hardware or remote vocoders.  I only offer USB device support for benchmarking purposes.
