### ISSUE TITLE
Feature Req: Logging to Text and WAV files

### ISSUE THREAD

**Issue by Tycho-S** [nostar/dudestar#33]
I was wondering if it would be possible to log incoming calls to text (e.g. the call and duration) and WAV files, it would be great to be able to hear what I missed when I'm not around. Or even better, it could be in the app as playable files perhaps.

Not sure if this is hard to do but I thought I'd ask. Thanks for all the work so far!

**Comment by nostar** [comment]
There is a bunch of commented out code that dumps audio to file and ambe data to file, that I used during early development.  Maybe someday I'll make that a user option.
