### ISSUE TITLE
Diagnosing connection problems

### ISSUE THREAD

**Issue by mlforcada** [nostar/dudestar#36]
I have built dudestar on my Ubuntu 20.04 laptop and droid-star in my phone. I believe they are based on the same code.
I can use M17 on both, and it seems to work (no QSO yet on dudestar).
However, I don't seem to be able to do DMR on dudestar, while it seems to work in droid-star.
One thing that is puzzling is that the hosts I can connect to in droid-star are not reachable from dudestar (for instance BM_Europe_2001), and vice-versa (DMR+_IPSC2-Catalunya).
But even if dudestar seems to connect and TX, I cannot see myself popping up on dashboards.
What would I need to do to diagnose my connection, besides calling or waiting for some channel to have activity?
Thanks a million!
Mikel

**Comment by mlforcada** [comment]
I installed dudestar in another Ubuntu 20.04 machine, step by step (I wrote the steps I took in https://github.com/nostar/dudestar/issues/8#issuecomment-734900336). M17 works nicely, had a quick QSO with K5WH; I tried DMR. My connection gets sometimes rejected in places where droid-star works nicely (BM_Europe_2001)... I am happy to test for the project if needed, just tell me where to start. Cheh

**Comment by nostar** [comment]
I have no issues like this so I can't help, except to say that you can not connect to any DMR server more than once with the same DMRID.  If you are testing back n forth with dudestar and droidstar by connecting using the same ID in both, that wont work.

**Comment by mlforcada** [comment]
I know I cannot connect twice. But even once, depending on the build, I get that my DestID to be correct or completely different to the TG I have selected. Happy to give you more details if that helps.
For instance, build b5bc0af today segfaults in one of my Ubuntu 20.04 boxes when I try to connect to DMR BM_Europe_2001 with my call sign and id and try to reach TG 91.

**Comment by nostar** [comment]
I tried connecting with your callsign and DMR ID and a blank password and connected fine at a couple different servers including 2001.  When you tried you got 'MSTNAK' which means you were refused by Brandmeister.  I don't know or care enough about brandmeister to know why they are refusing you, you will have to ask them.

I am well aware of many ways to crash dudestar, many during connecting.  I will address them all in time.

**Comment by mlforcada** [comment]
Thanks a million, Doug. 
I wonder what "MSTNAK" is. During the day I have been connecting to DMR sites more easily.
Thanks for the hard work.

**Comment by nostar** [comment]
It stands for something like "mobile station negative acknowledge" or something similar.  You received it at the stage of connect where your DMR ID and password (probably the server default defined in the DMRHosts.txt file) were sent to the server, so BM didnt like either your ID, password, or maybe location by IP, who knows.  I can't help with that part, but in latest git dudestar will pop up a dialog telling you that connection was refused, instead of crashing.  I will close this issue now.

**Comment by mlforcada** [comment]
Thanks a million!
