### ISSUE TITLE
Erratic DestID just after joining DMR host (build df9f854)

### ISSUE THREAD

**Issue by mlforcada** [nostar/dudestar#38]
When connecting to a DMR host, the DestID shown is erratic (sometimes the DestID used in the previous connection). When pressing PTT for the first time, it remains the same, but I believe the call goes out to the TG selected in the TG slot. After someone responds, things seem OK. 

If that helps, this behaviour is not shown by Droid-Star on Android.

**Comment by nostar** [comment]
This is a known issue, and happens erratically on all modes.  Its just random GUI data, not real info from the server/reflector.

**Comment by mlforcada** [comment]
Thanks! Do I have to understand there's nothing that can be leveraged from the fact that this works OK in Droidstar? I have not looked at the code, but they seem to share a similar UI.

**Comment by nostar** [comment]
It was a result of a rewrite of dudestar that had not yet been applied to droidstar.  A new droidstar release was posted tonight but this issue should be resolved in both. If it does appear still, it is not a big deal and I am not worried about it right now.

**Comment by mlforcada** [comment]
Thanks a million again, Doug.

**Comment by nostar** [comment]
Closing
