### ISSUE TITLE
Unable to build on Mint 13

### ISSUE THREAD

**Issue by Twilight-Logic** [nostar/dudestar#40]
I am unable to build this on my Linux mint system.

I have installed the dependencies listed:

> sudo apt-get install libqt5multimedia5-plugins libqt5serialport5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5

Curiously while installing I did get this:

Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/libmirsdrapi-rsp.so.2.13 is not a symbolic link

I am not installing on a Pi but on a Ubuntu/Debian based Linux distro!

This is the qmake output:

$ qmake
WARNING: /home/johnc/src/dudestar/dudestar.pro:145: Unescaped backslashes are deprecated.
Project MESSAGE: Warning: unknown QT: serialport

Since these were warnings I continued to make:

$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DVERSION_NUMBER="\"dee11ef\"" -DUSE_SWTX -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I. -I. -o audioengine.o audioengine.cpp
In file included from audioengine.cpp:1:0:
audioengine.h:5:10: fatal error: QAudioOutput: No such file or directory
 #include <QAudioOutput>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:566: recipe for target 'audioengine.o' failed
make: *** [audioengine.o] Error 1

I have PulseAudio installed.

**Comment by nostar** [comment]
You are using the run qmake, the one you ran appears to be for qt4.

**Comment by Twilight-Logic** [comment]
I think you are correct:

$ qmake -v
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

However I do have QT5 installed and when I try to install the QT5 version (qt5-qmake) it says it is already up to date. I found evetually that I could do:

qmake -qt=qt5

This runs qmake without errors and the compile runs a bit further, but still fails:

g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DVERSION_NUMBER="\"dee11ef\"" -DUSE_SWTX -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o dmrcodec.o dmrcodec.cpp
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DVERSION_NUMBER="\"dee11ef\"" -DUSE_SWTX -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o dudestar.o dudestar.cpp
In file included from dudestar.cpp:21:0:
ui_dudestar.h:13:10: fatal error: QtGui/QAction: No such file or directory
 #include <QtGui/QAction>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:1037: recipe for target 'dudestar.o' failed
make: *** [dudestar.o] Error 1

**Comment by nostar** [comment]
now you have a mess of files from both versions.
