### ISSUE TITLE
Replace MBELIB with MD380_VOCODER?

### ISSUE THREAD

**Issue by Tails98** [nostar/dudestar#42]
Hi Doug, can you replace mbelib with your md380_vocoder library?
It would make ambe audio sound great!
Just ask if me you need instructions for compiling on windows!

**Comment by nostar** [comment]
I already responded and closed your issue for this!  md380_vocoder can only run on an ARM processor.  Dont open an issue for this again.

**Comment by Tails98** [comment]
Doug, I have compiled md380_vocoder on windows 32/64 bit!
$ file md380_vocoder.o
md380_vocoder.o: Intel 80386 COFF object file, no line number info, not stripped, 5 sections, symbol offset=0x58e, 28 symbols

**Comment by nostar** [comment]
of course you can build it on any platform, all the c code does is make calls to ARM machine code. Do you really think the ARM machine code will execute on your non ARM processor?  Geezus.
