### ISSUE TITLE
Add AMBE server?

### ISSUE THREAD

**Issue by Tails98** [nostar/dudestar#44]
Hi Doug, I am wondering if you could add the ability to use a ambe server in dudestar?
EX: md380-emu on port 2470.
It would improve the ambe audio quality by a great amount!

**Comment by nostar** [comment]
I'm not interested in that. Bluedv and dvswitch already do that.  I am only interested open source and reverse engineered vocoders, and no remote server requirements.  I only offer USB AMBE support for benchmarking purposes.
