### ISSUE TITLE
Long passwords do not get accepted

### ISSUE THREAD

**Issue by LeFEAR** [nostar/dudestar#46]
I have a quite long password 22 char long and the application produces an error regardless that the settings are correct. 
people with shorter passwords have no issue 

9 char (works) vs 22 char (fails) password 

Thanks

**Comment by nostar** [comment]
I just tested with both of my IDs 2 long passwords.  One 22 chars and one 23 chars (ThisIsAVeryLongPasswrd and ThisIsAVeryLongPassword) and both work fine for me, tested on a couple different servers.  I don't know what to tell you.

**Comment by LeFEAR** [comment]
Just to be clear. 

The password is the Hotspot security password ? or the login to BM website self care account password?

Because I couldn't find any mention to it.

Thanks 

p.s. add it to the Readme please

**Comment by nostar** [comment]
Add what to the README?  I don't know what your question is now.

**Comment by s58DB** [comment]
Yes, enter hotspot security password.

**Comment by LeFEAR** [comment]
> Add what to the README? I don't know what your question is now.

Add in the Readme , that the password is the Hotspot security password.

okay so issue solved i was using other credentials. 

Thanks 
73 DE

**Comment by nostar** [comment]
Ok, I see now.  I have plenty of things that need to be added to README.  One day I'll sit down and create some better documentation.  Closing this issue.

**Comment by LeFEAR** [comment]
perfect :D Thanks
