### ISSUE TITLE
Trying to use for first time, and Windows program magically disappears when I click on CONNECT

### ISSUE THREAD

**Issue by greetrob753** [nostar/dudestar#49]
I tried this, and the application immediately "disappears" from windows when I click on the CONNECT button. Build version e9d207b. Does it work for anyone else? Running on Windows 10 professional. Note options I tried to use are with my DMR ID/password, Parrot 9990, private call. I have bluetooth headphone/mic on. When I click on "connect" the windows program disappears.
![dude](https://user-images.githubusercontent.com/58054127/101261467-64c61780-3705-11eb-98ce-709fa6296a76.jpg)
![dude2](https://user-images.githubusercontent.com/58054127/101261477-83c4a980-3705-11eb-963f-f567200c184c.jpg)

**Comment by greetrob753** [comment]
I was told on FB that I was missing the master server.  Things are working better so far, but still working on hearing something.  Just beginner mistakes probably.

**Comment by nostar** [comment]
The latest git displays a dialog telling you to choose a host instead of crashing.  Closing.
