### ISSUE TITLE
Malformed Transmit Audio on Mac OS X 

### ISSUE THREAD

**Issue by djshadowxm82** [nostar/dudestar#50]
## Expected Behavior
Transmit audio through software vocoder to be wellformed and intelligible (as much as it can be on a digital codec as such)

## Actual Behavior
Transmit audio with mbelib does not emit intelligible audio of any sort going out to the network. Receive audio using the same software vocoder library however does work properly.

## Steps to Reproduce the Problem

  1. Compile on Mac OS X
  2. Call -L/usr/local/Cellar/mbelib/1.3.0/lib installed and symlinked via Brew
  3. Attempt to transmit audio and receive garbage back from parrot and multiple confirmed contacts of same with real individuals.
  

## Specifications

  - Git Version: 41370b8
  - Platform: 2017 MacBook Air Mac OS X 11.0.1
  - Subsystem: QT 5.12.1, MBELib 1.3.0

**Comment by TychoSchenkeveld** [comment]
I have this also, sorry for not raising it myself but I was very busy

**Comment by nostar** [comment]
Both of you try latest git and report your results, along with as many details about your hardware as possible i.e. platform and audio hardware available to test.  Also provide details on how you installed all of your development tools (Xcode, Qt, cmake, mbelib, etc)

This changes makes TX work perfectly for me using an MPow USB headset for TX, but the built-in microphone sounds very bad and overwhelmed with what sounds like background noise on a MacBook Pro 13 macOS 10.15.17.

**Comment by TychoSchenkeveld** [comment]
Oh great, thanks, will try it tomorrow! FWIW I was also using a USB microphone.

I installed Xcode from the app store, Qt and cmake from brew and mbelib from the github link you recommended. Will try the latest tomorrow!

**Comment by djshadowxm82** [comment]
The issue persists for me. I've attempted the change with #dab5185,  with the built in mic (which i've had no issues with anything else as I use it on discord, it shouldn't have an issue with this nor do I have anything else).

Also, I've altered the .pro file to include mbelib from brew installation that was linked over and got rid of the path warnings for no windows machine builds.

win32:LIBS += -LC:\Qt\mbelib\build_x32 -LC:\Qt\mbelib\build_x64 -lmbe
macx:LIBS += -L/usr/local/Cellar/mbelib/1.3.0/lib -lmbe

Development environment is as follows

## Test Environment 

  - Git Version: #dab5185
  - Platform: 2017 MacBook Air Mac OS X 11.0.1
  - Subsystem: QT 5.12.2, MBELib 1.3.0,QMake version 3.1,GNU Make 3.81,clang-1103.0.32.59

##Versions Verbose
qmake -v
QMake version 3.1
Using Qt version 5.15.2 in /usr/local/Cellar/qt/5.15.2/lib

make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

 clang++ -v
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by nostar** [comment]
This change seems to only work for USB audio devices.  That's all I have for now.

Adding the path to your mbelib install in fine, simple and effective, but it doesn't need to be mentioned here since it is not a dudestar issue:  

https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html

Homebrew made a really bad choice for their library install locations.  The source install of mbelib goes into the conventional location for locally installed libraries '/usr/local/lib/'.   Just like on Linux, I have configured my linker with that path so that this and any other software build will always find any locally installed libraries.  The windows path warnings are harmless and specific to my windows setup for creating the windows build.

**Comment by nostar** [comment]
The problem appears to be a problem in the Qt interface to the macOS coreaudio driver, so a real fix may be a while.  The built in microphone will only capture correctly at a sample rate of 44.1KHz, and the USB headset (and hopefully all other external audio devices) will only capture at a rate of 48KHz, even though the driver for both reports supporting all the standard rates, and works fine with playback at 8Khz, the required audio rate for all ham digital modes.  48KHz is an exact multiple of 8KHz so the hack creates a perfect 8KHz sample, but for 44.1KHz the closest multiple below is 40KHz so the result is a transmission of a lower pitched and slower version of your voice.  Also for very long transmissions, the delay between your speech and the transmitted audio continues to increase.  

For the hack to detect the built in mic, it needs to report the exact text "Built-in Microphone".  If this is not the case on anyone's mac, reply back with all of the debug output on the shell.  This hack is in latest git.

**Comment by djshadowxm82** [comment]
Well with this build, I don't have the scrambled audio anymore, but its definitely keying up with no audio at all now. So not sure what we can do to fix this if at all without support from QT

```
Playback device name =  "Built-in Output"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(48000, 96000, 88200, 44100)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using playback device Built-in Output
Capture device name =  "Built-in Microphone"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(48000, 96000, 88200, 44100)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using recording device Built-in Microphone
```

**Comment by nostar** [comment]
Thats because Mojave and onwards require permission to use the microphone.  You need to launch the application from the Terminal so that the Terminal will request permission, since there is no provision to request permission in dudestar right now.  This doesn't mean use 'open dudestar.app' either. From the source directory run:
```
dudestar.app/Contents/MacOS/dudestar
```
The first time you TX you will get a prompt requesting permission from the Terminal to use the microphone.  It should work after that.

**Comment by djshadowxm82** [comment]
> Thats because Mojave and onwards require permission to use the microphone. You need to launch the application from the Terminal so that the Terminal will request permission, since there is no provision to request permission in dudestar right now. This doesn't mean use 'open dudestar.app' either. From the source directory run:
> 
> ```
> dudestar.app/Contents/MacOS/dudestar
> ```
> 
> The first time you TX you will get a prompt requesting permission from the Terminal to use the microphone. It should work after that.

I've been launching it that way, I never got a prompt.

**Comment by rd0fun** [comment]
I did a new fetch from git and a qmake and make just a few moments ago.

qmake had the usual warning
make had several warnings from code

all compiled, mbe lib found (in /usr/locall/lib). I modified nothing in .pro

transmitted on DMR 9990 with private checked, did not get parrot (got angry replies). and apparently audio was incoherent.

I launched the app with dudestar.app/Contents/MacOS/dudestar, was not prompted for access to mic.

**Comment by nostar** [comment]
mbelib was not found on your system, it is now included in the source.

What are the details of your machine and what audio input hardware are you using?  What is it called exactly by dudestar?

**Comment by rd0fun** [comment]
ESSID ==  "2"
dmrid_text_changed() called s ==  "9990"
CONN: 59 53 46 50 4e 32 57 4f 4a 20 20 20 20 20 
RECV: 59 53 46 50 52 45 46 4c 45 43 54 4f 52 20 
Playback device name =  "MacBook Pro Speakers"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(44100, 88200, 48000, 96000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using playback device MacBook Pro Speakers
Capture device name =  "MacBook Pro Microphone"
(LittleEndian, BigEndian)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
("audio/pcm")
(44100, 88200, 48000, 96000)
(8, 16, 24, 32, 64)
(SignedInt, UnSignedInt, Float)
Using recording device MacBook Pro Microphone

**Comment by rd0fun** [comment]
<img width="264" alt="Screen Shot 2020-12-14 at 8 58 27 AM" src="https://user-images.githubusercontent.com/72984819/102089663-894b7f00-3dea-11eb-9378-e7b0185b5b49.png">

**Comment by nostar** [comment]
Try latest git

**Comment by rd0fun** [comment]
Working great on build 8da12a3.

Fantastic work! Love it. Thank you.

**Comment by nostar** [comment]
Read my comment above about how this hack works regarding your built in mic.  I suggest a USB headset, since it works perfectly with this hack until I or Qt come up with a real fix.

**Comment by rd0fun** [comment]
> Read my comment above about how this hack works regarding your built in mic. I suggest a USB headset, since it works perfectly with this hack until I or Qt come up with a real fix.

Will do! Thank you again. Very nice. LOVE this project very much!

**Comment by rd0fun** [comment]
> Qt interface to the macOS coreaudio driver, so a real fix may be a while. The built in microphone will only capture correctly at a sample rate of 44.1KHz,

Does it work with PulseAudio? That is to ask, can PulseAudio be used cross-platform and have the correct sample rate?

**Comment by Tycho-S** [comment]
I can confirm this works well now! With USB headset. Thanks so much for the fix!
