### ISSUE TITLE
Custom DMR Servers

### ISSUE THREAD

**Issue by VE3RD** [nostar/dudestar#54]
I have two custom servers I want to connect to. They do not appear in the standard dmr hosts file and both have a long password 15 and 16 characters. Is the DMR Hosts file available that I can add to it, or is there a way to input custom server credentials
Windows Build 41370b8

**Comment by nostar** [comment]
You can manually modify the host files if you want.  On Windows they are in /Users/<username>/AppData/Local/dudestar.
