### ISSUE TITLE
No TX in DMR

### ISSUE THREAD

**Issue by VE3RD** [nostar/dudestar#55]
I select a DMR Server, Cc1, TS2
I enter my call and dmr id, and TG
I press connect and see the host connection line at the bottom of the screen
I hear audio from the server on the selected TG
I press the TX button which turns red, but the server does not register any data packets

**Comment by nostar** [comment]
All I can say with this info is user error.

**Comment by VE3RD** [comment]
can you spot where I made a user error
Mode-DMR
Call=VE3RD
Server Selected from Hostfile
Password= passw0rd, also tryed leaving it blank after selecting the server to pick it up from the DMRHosts file.
TG-3023
CC=1
TS=2
at the bottom I see the Host Server with the increasing ping count
and incoming data fields fill in when a user is using the selected server TG

![image](https://user-images.githubusercontent.com/43919012/102002406-3b3f5a00-3cca-11eb-8ac2-1b4d63777786.png)

**Comment by nostar** [comment]
ESSID doesnt work on TGIF with the version you have.  Clear out the ESSID field or get the latest version on github

**Comment by VE3RD** [comment]
Removed esid and it works
Thanks

I thought I had the most recent, as I did download it from Github. It said it was 6 days 
I see now the newest is only a couple of hours old
Trying it Now

**Comment by VE3RD** [comment]
Everything Working Great!!
Thanks
