### ISSUE TITLE
Please add a DMR the Master HBLINK.

### ISSUE THREAD

**Issue by ea5gvk** [nostar/dudestar#6]
Please add all the DMR HBLINK servers that are also listed on the piston.
Thank you very much.

http://www.pistar.uk/downloads/DMR_Hosts.txt

**Comment by nostar** [comment]
HB servers have been added.

**Comment by sp2ong** [comment]
But maybe it will useful add possible read defined own DMR local server. If exist local  file DMR_Hosts.txt it will add to loaded from network DMR Hosts. We have used local DMR servers based on HBLink but not exist in Pi-Star Database DMR Hosts etc
