### ISSUE TITLE
Crashes Consistently on TX

### ISSUE THREAD

**Issue by el1teindustries** [nostar/dudestar#60]
Howdy -
Running version git build 21a818e 64-bit, clicking on transmit button crashes the application when connected to either DMR or P25 networks. (I haven't tried any others) I have entered all details (Callsign, DMR ID, Hotspot security etc) and am connected to BM or P25NX. Edit: This happens with both x86 and x64 executables.
Crash event in application log:

Faulting application name: dudestar_x64.exe, version: 0.0.0.0, time stamp: 0x5fdbe941
Faulting module name: dudestar_x64.exe, version: 0.0.0.0, time stamp: 0x5fdbe941
Exception code: 0xc0000005
Fault offset: 0x00000000003a3ab0
Faulting process id: 0x51c
Faulting application start time: 0x01d6d4dd857b5845
Faulting application path: C:\Users\user\Downloads\dudestar_x64.exe
Faulting module path: C:\Users\user\Downloads\dudestar_x64.exe
Report Id: 447bc317-4919-498e-8241-3b919f99f347
Faulting package full name: 
Faulting package-relative application ID: 

I've attached dxdiag output in case that's helpful.

Thanks!
Paul 
W0PWS
[DxDiag.txt](https://github.com/nostar/dudestar/files/5713106/DxDiag.txt)

**Comment by nostar** [comment]
Your computer doesn't have an audio capture device, or at least its not being detected by your OS.  A USB headset like an Mpow works well with this.

**Comment by el1teindustries** [comment]
> Your computer doesn't have an audio capture device, or at least its not being detected by your OS. A USB headset like an Mpow works well with this.

Great, thanks. I have a headset around here somewhere. 

Thanks!
Paul

**Comment by el1teindustries** [comment]
Duh ... I can't believe I didn't realize that my built-in mic wasn't being recognized. 
Works great when you actually have an input device. Thanks again. You can close this out.
