### ISSUE TITLE
Feature Req: The ability to configure talkgroup / reflector memories

### ISSUE THREAD

**Issue by JimGat** [nostar/dudestar#61]
It would be nice to be able to configure memories and even give memory names to the TG memory.  
Just basic memories would be nice.  If you wanted to go even further you could remember the Mode and Host Parameters. 

Very good implementation so far BTW!   Keep up the good work!

**Comment by nostar** [comment]
Mode, host, module, and all the settings are already remembered, as is the host that was selected when it was last closed.

**Comment by rd0fun** [comment]
Does that include a password per host? For example, DMR BM_UnitedStates_201 password is likely different than DMR TGIF_Network. Are host/password pairs saved? It appears there is only one password for all hosts.

**Comment by JimGat** [comment]
My Request was more of a new feature where you have memories similar to a radio where you have a tab or something with a set of buttons that are your most used Talkgroups, fusion reflectors, d-star, etc.   That way you can quickly switch between them.   possibly a disconnect and reconnect with the new values.   This is not a bug or a must-have.  Just a suggestion.  The point Dudestar is at now is awesome!
