### ISSUE TITLE
Refused connections 

### ISSUE THREAD

**Issue by mlforcada** [nostar/dudestar#62]
After a completely clean installation of build 21a818e I am not able to access many DMR hotspots that worked for me (I get the message "DMR connection refused.  Check callsign, DMR ID, or password"). Maybe there is something I have to add in the new configuration with respect to the previous version that did not have the tab-based UI. Could you please help? Thanks a million.

P.S. Release tagged 41370b8 works. Later releases don't.

**Comment by nostar** [comment]
Earlier versions had my own personal info hard coded into the DMR config.  That is all removed now and it is up to you to enter your own config data.  It is not a dudestar issue to tell you what that data is, you need to figure that one for yourself.

**Comment by mlforcada** [comment]
OK, thanks. Besides my call sign and DMR ID, which I have provided, what else do I need for DMR? The passwords to each host seem to be stored in DMRHosts.txt, and they seem correct. What additional details may I be missing?
The new version of Droidstar does not have this problem, by the way. 
This an example of a dudestar config that works with 41370b8:
```
PLAYBACK:OS Default
CAPTURE:OS Default
MODE:DMR
REFHOST:
DCSHOST:
XRFHOST:
YSFHOST:ES-WiresX - Wires X Spain
DMRHOST:BM_Brazil_7242
P25HOST:
NXDNHOST:
M17HOST:M17-M17
MODULE:A
CALLSIGN:EA5IYL
DMRID:2145893
ESSID:None
DMRPASSWORD:
DMRTGID:214009
MYCALL:
URCALL:
RPTR1:
RPTR2:BM_Brazil_7242 A
USRTXT:
```
