### ISSUE TITLE
TX duration wrong on hbmonitor / hblink

### ISSUE THREAD

**Issue by Artemia76** [nostar/dudestar#63]
Strange behavior on HBLink networks : TX duration seem to be multiply by 6 or 10 

https://i.imgur.com/0gkJaUi.png

**Comment by nostar** [comment]
I have no idea what this image is.

**Comment by Artemia76** [comment]
sorry , you can see on the image, my transmission ( FS76G1) using dudestar , TX time is more 10X than real time. Behind server is HBLink and web part is HBmonitor based.

**Comment by nostar** [comment]
![hbmon](https://user-images.githubusercontent.com/3847102/102722592-0d60a380-42d0-11eb-8f43-b8750af03ea8.png)

I tested at multiple sites and there is no problem with dudestar.  No DMR client sends tx time information, it is calculated by the server.
