### ISSUE TITLE
Please add network prime.tgif.network

### ISSUE THREAD

**Issue by n5sap** [nostar/dudestar#64]
Hello. There is a server TGIF network has running in parallel yet separate instances for DMR. The big difference is TGIF.network uses a default password of password however on the prime.tgif.network hotspot security is enabled. It would be invaluable to add prime.tgif.network! Thanks

**Comment by lordkane** [comment]
have found on windows C:\Users\"yourusername"\AppData\Local\Dudestarx64 or
                                      C:\Users\"yourusername"\AppData\Local\Dudestarx86

**Comment by nostar** [comment]
I pull the DMR hosts file from the pistar website.  If it gets added to that file, it will be available.
