### ISSUE TITLE
Please add Vox function

### ISSUE THREAD

**Issue by lordkane** [nostar/dudestar#65]
Hi it is possible to add Vox function in Dudestar

**Comment by nostar** [comment]
Dudestar will always require a button to be pressed by the user.  It is important to me that it never transmits unattended.  Thats is also why I do not allow toggle of TX button.

**Comment by lordkane** [comment]
i want put a radio together with dudestar ... i need vox for it

**Comment by nostar** [comment]
no

**Comment by scresante** [comment]
> i want put a radio together with dudestar ... i need vox for it

The beauty of open-source is that anybody can fork it and add new features. If you want this feature, add it. If you do, I'd be interested. I have a small corner-case where vox would be good, that I operate in 10% of the time. 

Overall, vox causes more problems than it solves.
