### ISSUE TITLE
Please add hardware PTT detection

### ISSUE THREAD

**Issue by Alpamayo57** [nostar/dudestar#67]
It would be super cool if you would add this very useful function like they did in Peanut and Echolink.
Also the ability to detect a bluetooth ptt button would be  welcome.
Thank you

**Comment by nostar** [comment]
I don't own any PTT hardware or android radios, so I have no plans for this at this time.

**Comment by Alpamayo57** [comment]
Fine. But even the ability to map  Volume+ or Volume- button would do.
