### ISSUE TITLE
Windows build issue : :-1: erreur : Cannot find = after : in macro substitution

### ISSUE THREAD

**Issue by Artemia76** [nostar/dudestar#69]
I'm trying to build dudestar on windows through QT  5.12.2 and I get : 
:-1: erreur : Cannot find = after : in macro substitution. in E:\devel\git\build-dudestar-Desktop_Qt_5_15_2_MSVC2019_64bit-Debug\Makefile.Debug line 344

Any idea ?

**Comment by nostar** [comment]
broken build system

**Comment by Artemia76** [comment]
Ok I realize that the windows build is GCC based through mingw.
I success to build it on MSVC compiler with some modifications : 
- on dudestar.pro file , I add system command to get git version and remove this issue.
- on C part sources, (codec 2 , mbelib, etc) dynamic array(like float array[size]; ) are forbidden on MSVC, So I added new and  delete statements to replace them by : 
`float* array = new float[size];
{code}
delete[] array;`

You can check on my fork https://github.com/Artemia76/dudestar/tree/backoffice
If your are interested I can make pull request on your project

**Comment by nostar** [comment]
FYI you are free to do anything you want with your fork of any open source project on github, but I will only support open source GCC based compilers.
