### ISSUE TITLE
Make file and also Windows make of VS .sln files don't seem to be included

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [nostar/dudestar#71]
Make file and also Windows make of VS .sln files don't seem to be included

Also, Can you please document how to build for Windows.

Ideally the the whole build dev installation and build process needs to be documented in more detail

**Comment by nostar** [comment]
I do not support nor condone Microsoft compilers, or provide any Windows specific support whatsoever. This is a GCC based Linux project first and foremost. It builds and runs on Windows and macOS with the proper GCC/CLang based build system, but that is on you to set up.

Ideally you should be using a real OS.

**Comment by rogerclarkmelbourne** [comment]
"I do not support nor condone Microsoft compilers, or provide any Windows specific support whatsoever"

https://github.com/nostar/dudestar/releases/tag/dbe3ec9 ???

**Comment by nostar** [comment]
You can't read?

**Comment by rogerclarkmelbourne** [comment]
(LOL)
