### ISSUE TITLE
Allstarlink connection ?

### ISSUE THREAD

**Issue by devnulling** [nostar/dudestar#76]
Would anyone be able to provide more details on what needs to be changed on a typical allstarlink node to get dudestar to connect? (iax.conf / extensions.conf changes?)

There doesn't seem to be any good documentation about connecting IAX2 with Allstarlink (or my googlefu is just weak).

**Comment by VA3MPM** [comment]
Following

**Comment by nostar** [comment]
Allstar node setup should be discussed at an allstar/asterisk forum or list.

**Comment by devnulling** [comment]
@nostar have you used this with allstar at all? There seems to be at least a bug related to the password authentication with asterisk at least from what I found with basic testing. Just looking if someone has used this successfully.

**Comment by nostar** [comment]
Yes I use it every day, works fine.
