### ISSUE TITLE
Please add DMR network 

### ISSUE THREAD

**Issue by n5sap** [nostar/dudestar#77]
Please add to the list of available servers in dudestar (android)
Prime.tgif.network. same default values as tgif.network  this will be an invaluable addition to help us test the new network please

**Comment by nostar** [comment]
It's been added to the DMR hosts file used by dudestar/droidstar.  Click 'update hosts' to add it to the list.

**Comment by n5sap** [comment]
Awesome thanks ever so much
________________________________
