### ISSUE TITLE
Compilation error on macOS

### ISSUE THREAD

**Issue by jeanboutros** [nostar/dudestar#78]
Hello,
I am trying to compile dudestar on MacOS Big Sur v11.1 and it has been working until I pulled the latest changes today and I started getting the below error:

`/Library/Developer/CommandLineTools/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/jean/opt/anaconda3/lib -o dudestar.app/Contents/MacOS/dudestar CRCenc.o DMRData.o Golay24128.o SHA256.o YSFConvolution.o YSFFICH.o ambe.o ambe3600x2400.o ambe3600x2450.o audioengine.o cbptc19696.o cgolay2087.o chamming.o codebooks.o codec2.o kiss_fft.o lpc.o nlp.o pack.o qbase.o quantise.o crs129.o dcscodec.o dmrcodec.o dudestar.o ecc.o httpmanager.o iaxcodec.o imbe7200x4400.o aux_sub.o basicop2.o ch_decode.o ch_encode.o dc_rmv.o decode.o dsp_sub.o encode.o imbe_vocoder.o math_sub.o pe_lpf.o pitch_est.o pitch_ref.o qnt_sub.o rand_gen.o sa_decode.o sa_encode.o sa_enh.o tbls.o uv_synt.o v_synt.o v_uv_det.o levelmeter.o m17codec.o main.o mbedec.o mbeenc.o mbelib.o nxdncodec.o p25codec.o refcodec.o serialambe.o xrfcodec.o ysfcodec.o micpermission.o qrc_dudestar.o moc_audioengine.o moc_dcscodec.o moc_dmrcodec.o moc_dudestar.o moc_httpmanager.o moc_iaxcodec.o moc_levelmeter.o moc_m17codec.o moc_nxdncodec.o moc_p25codec.o moc_refcodec.o moc_serialambe.o moc_xrfcodec.o moc_ysfcodec.o moc_micpermission.o   -framework AVFoundation -L/Users/jean/opt/anaconda3/lib -lQt5Multimedia -framework DiskArbitration -framework IOKit -lQt5Widgets -lQt5Gui -lQt5Network -lQt5SerialPort -lQt5Core -framework OpenGL -framework AGL 
Undefined symbols for architecture x86_64:
  "_objc_msgSend", referenced from:
      MicPermission::check_permission() in micpermission.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dudestar.app/Contents/MacOS/dudestar] Error 1`

Any thoughts?

**Comment by nostar** [comment]
No other than you build system is broken.  I have Xcode 12.3 installed and Qt 5.15.2 from Macports.  I run /opt/local/libexec/qt5/bin/qmake.  I dont know what anacond3 is but that shouldnt be in there are clang++ is being run from the wrong location in your build. There is some native obj-C code included now to request microphone permission, and your build cant find obj_msgSend, part of the core mac obj-C runtime lib.

**Comment by jeanboutros** [comment]
Well, thank you for the quick answer.
You were totally right about anaconda. I was using the wrong qmake.
I used homebrew to install qt5 then added it to my path and rebuilt the project and now it's working.
Thanks a lot.

**Comment by nostar** [comment]
FYI I prefer to not put qmake in path and instead I call the specific qmake that I want by the full pathname.
