### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by ph0dv** [nostar/dudestar#8]
Hello,

I get this error on compiling. What i do after installing dependency's:

git clone https://github.com/nostar/dudestar.git
cd dudestar
mkdir build
cd build
qmake ..
make

In file included from ../dudestar.cpp:18:
../dudestar.h:31:10: fatal error: flite/flite.h: No such file or directory
 #include <flite/flite.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:710: dudestar.o] Error 1

Any idea?

Kind regards an 73's
PH0DV
Dick

**Comment by ph0dv** [comment]
sudo apt-get install flite-dev did do this job

**Comment by nostar** [comment]
Yes, you figured it out.  I usually have the line #define USE_FLITE in 
dudestar.h commented out so the flite text to speech library is not 
used, but I forgot in my last commit.

-Doug

**Comment by mlforcada** [comment]
Thanks a million, Doug.
I wrote this 'guide' by installing in another machine. Perhaps it's useful to some visitors or to complete the README.md
```
# I'm assuming you have git and essential building stuff such as make installed 
#
#install dependencies    
sudo apt install cmake qtchooser qt5-qmake libqt5multimedia5-plugins libqt5serialport5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5 flite-dev libasound2-dev
# move to wherever we want to build things
cd MY_GIT_DIRECTORY
# we need to compile mbelib first
git clone https://github.com/szechyjs/mbelib
cd mbelib                           # Move into source folder
mkdir build                         # Create build directory
cd build                            # Move to build directory
cmake ..                            # Create Makefile for current system
make                                # Compiles the library
sudo make install                   # Library is installed into computer
# clone repository
git clone https://github.com/nostar/dudestar
#build
qmake
make
#run and try, your mileage may vary
./dudestar 
```

**Comment by mlforcada** [comment]
This build has problems with DMR and does not sound too good on YSF (I tried). In DMR, if I connect to a certain TG, it sends to a different TG, that has nothing to do with what I typed.
Installed as described above, DUDE-Star git build b5bc0af. Ubuntu 20.04. 
Sorry for the deluge of issues, Doug. Thanks!

**Comment by nostar** [comment]
Maybe you are pulling commits during a transfer from dev to master I did yesterday and today and have some bad builds.  I have no issues with DMR talkgroups like you describe.

**Comment by mlforcada** [comment]
It'd be great to tag stable releases in some way.
Just pulled and rebuilt f2a296d. 
Tried connecting in DMR to BM_Europe_2001 and TG91 with my DMR id. It systematically segfaults like this:
dmrid_text_changed() called s ==  "91"
```
CONN: 52 50 54 4c 00 20 be 65 
RECV: 52 50 54 41 43 4b 12 51 61 83 
SEND: 52 50 54 4b 00 20 be 65 8f bd 06 de 33 62 9a 51 9b c5 ae 85 e3 cf 5d 75 d7 00 38 6c 17 a2 55 72 61 33 30 b0 d6 b9 db df 
RECV: 4d 53 54 4e 41 4b 00 20 be 65 
Violació de segment (s'ha bolcat la memòria)
```
when connecting to other Hosts it tries "Connecting..." . When I press "on "Connecting", it segfaults again with
```
dmrid_text_changed() called s ==  "91"
CONN: 52 50 54 4c 00 20 be 65 
Violació de segment (s'ha bolcat la memòria)
```

**Comment by mlforcada** [comment]
I have tried on a different Ubuntu 20.04 box: make clean, git pull (f2a296d), qmake, make.
The results are quite different.
When I try the same connection as in my previous comment, I get connected to DestID 21986 until I PTT. Ping numbers are very high (9949308560 or such).
What should I check in the two machines to see what's the difference?

**Comment by nostar** [comment]
USE_FLITE is commented out in latest git.  Only uncomment it if you you know how to install flite and use it properly.
