### ISSUE TITLE
Droidstar no longer working in background

### ISSUE THREAD

**Issue by Skinoku** [nostar/dudestar#83]
Hi,
I saw that in the latest version of droidstar the application cannot be run in background without disconnecting from the server.
Is this intentional or it is an issue?
It was really cool to monitor talkgroups on the go without having to always keep the screen on bevause such it's a waste of enery and the device can no longer be used for something else. (For example texting while listening).
Oleds may experience screen image retention if displaying the same image for a long period of time.
Thanks

**Comment by nostar** [comment]
This is intentional.  I will add a user selectable option to allow this later, with a notification icon to indicate that it is still running.  Too many people were leaving it running without knowing about it.
