### ISSUE TITLE
Autofill RPTR1 field

### ISSUE THREAD

**Issue by nolith** [nostar/dudestar#93]
Hello, thanks for writing this software.

Today I was testing it on D-STAR and I had an hard time figuring out how to set RPTR1 field.

Looking at the reflector dashboard I saw that my connection was "MYCALLSING-REFLECTOR_MODULE" setting it manually allowed me to have a QSO.

I think I have 2 question/proposal here:

1. why my "hotspot" module isn't always the same? Why using the reflector module?
1. could it be possible for dudustar to set it automatically when I change the reflector module?

Thank you

**Comment by nostar** [comment]
I don't know what you mean by hotspot and repeater module.  I currently set RPTR2 upon connect to the reflector and module that is connected to.  I leave the rest to be set manually, as I prefer the lowest level of control by the user.  Even RPTR2 can be changed after connect, if desired. My typical settings using a connection to REF625A as an example would be:
```
MYCALL: AD8DP
URCALL: CQCQCQ
RPTR1: AD8DP X  (the X is arbitrary and can be anything on any reflectors I frequent)
RPTR2: REF625A (set upon connect)
```

**Comment by nolith** [comment]
Thanks for your answer @nostar 

I'll take your example to explain my point.

If you connect to `REF625` module `A`, then in order for your QSO to be routed to it `RPT2` must be `REF625A`. And this is already the case.

As far as I understood it, dudestar is acting as an hotspot connecting directly to the reflector. When I check the reflector dashboard, I can see that my dudestar connection comes from a node with my callsign and a module that **always matches the module of the reflector I'm connecting to**.

In your example it will be`AD8DP  A`. In order to be routed correctly to `REF625A`, the `RPT1` field must be `AD8DP  A`.

So what I'm asking here is if either we could automatically set the `RPT1` field, because every time I change module on the target reflector, I have to adjust it. Or if we can set the desired dudestar module somewhere else, so that it will not change when I change the reflector module I'm connecting to.

I hope my request makes more sense now.

**Comment by nostar** [comment]
As I said before , I always use the letter X in my RPTR1 field (AD8DP X) and i connect to all REF, DCS,and XRF reflecors and RX/TX with no problem.  The one that matters is RPTR2, so if I change from REF625A to REF089C, then the only thing that needs to change is RPTR2 from REF625 A to REF089 C, which is currently done automatically.  My RPTR1 always stays set to AD8DP X and there are no problems.

That being said , it is not a problem to autoset the other fields for convenience like I do RPTR2, and I will add that in a future commit.

**Comment by nolith** [comment]
Oh , I was under the assumption the `X` was a placeholder in your example. I used to change it to match the value I saw in my reflector dashboard, but if this is not the case I have no problem in leaving it empty.

Thanks for explaining
